-- ### ROLE:
CREATE TABLE `roles` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` ENUM('ADMIN','EDU','PARENT','CHILD') NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


-- ### NOTIFICATIONS:
CREATE TABLE `notifications` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`MESSAGE` VARCHAR(500) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`TYPE` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`IS_READ` ENUM('Y','N') NOT NULL DEFAULT 'N' COLLATE 'utf8mb4_general_ci',
	`CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`USER_ID` INT(10) NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_notifications_users` (`USER_ID`) USING BTREE,
	CONSTRAINT `FK_notifications_users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


-- ### USERS:
CREATE TABLE `users` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`LAST_NAME` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`USERNAME` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`PASSWORD` VARCHAR(4000) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PASSKEY` INT(10) NULL DEFAULT NULL,
	`PHONE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`IS_SUBSCRIBED` ENUM('Y','N') NULL DEFAULT 'N' COLLATE 'utf8mb4_general_ci',
	`CREATED_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`ROLE_ID` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_users_roles` (`ROLE_ID`) USING BTREE
)
COMMENT='These users for booknest website'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


-- ### CHILDREN:
CREATE TABLE `children` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`NAME` VARCHAR(400) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`DOB` DATE NOT NULL,
	`AGE` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`AVATER` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CREADTED_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`USER_ID` INT(10) NULL DEFAULT NULL,
	`ROLE_ID` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_children_users` (`USER_ID`) USING BTREE,
	INDEX `FK_children_roles` (`ROLE_ID`) USING BTREE,
	CONSTRAINT `FK_children_roles` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_children_users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


-- ### BOOKS:
CREATE TABLE `books` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`DESCRIPTION` VARCHAR(4000) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`AUTHOR` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`LANGUAGE` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`AGE_GROUP` ENUM('4-6','7-9','10-12') NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`COVER` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`FILE_PATH` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`IS_ACTIVE` ENUM('Y','N') NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CREATED_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;



-- ### FAVORITES:
CREATE TABLE `favorites` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`USER_ID` INT(10) NOT NULL,
	`BOOK_ID` INT(10) NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_favorites_users` (`USER_ID`) USING BTREE,
	INDEX `FK_favorites_books` (`BOOK_ID`) USING BTREE,
	CONSTRAINT `FK_favorites_books` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_favorites_users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


-- ### QUIZZES:
CREATE TABLE `quizzes` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_general_ci',
	`DESCRIPTION` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CREATED_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`USER_ID` INT(10) NULL DEFAULT NULL,
	`BOOK_ID` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_quizzes_books` (`BOOK_ID`) USING BTREE,
	INDEX `FK_quizzes_users` (`USER_ID`) USING BTREE,
	CONSTRAINT `FK_quizzes_books` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`) ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT `FK_quizzes_users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

-- ### QUESTIONS:
CREATE TABLE `questions` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`QUESTION` TEXT NOT NULL COLLATE 'utf8mb4_general_ci',
	`TYPE` VARCHAR(50) NOT NULL COMMENT 'e.g., multiple_choice, true_false' COLLATE 'utf8mb4_general_ci',
	`CREATED_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`QUIZ_ID` INT(10) NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `QUIZ_ID` (`QUIZ_ID`) USING BTREE,
	CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`QUIZ_ID`) REFERENCES `quizzes` (`ID`) ON UPDATE NO ACTION ON DELETE CASCADE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

-- ### OPTIONS:
CREATE TABLE `options` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`OPTION` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`IS_CORRECT` ENUM('Y','N') NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`QUESTION_ID` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `FK_options_questions` (`QUESTION_ID`) USING BTREE,
	CONSTRAINT `FK_options_questions` FOREIGN KEY (`QUESTION_ID`) REFERENCES `questions` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

-- ### SCORE:
CREATE TABLE `scores` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`QUIZ_ID` INT(10) NOT NULL,
	`CHILD_ID` INT(10) NOT NULL,
	`SCORE` DECIMAL(5,2) NOT NULL,
	`COMPLETED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `QUIZ_ID` (`QUIZ_ID`) USING BTREE,
	INDEX `CHILD_ID` (`CHILD_ID`) USING BTREE,
	CONSTRAINT `scores_ibfk_1` FOREIGN KEY (`QUIZ_ID`) REFERENCES `quizzes` (`ID`) ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT `scores_ibfk_2` FOREIGN KEY (`CHILD_ID`) REFERENCES `children` (`ID`) ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT `scores_chk_1` CHECK ((`SCORE` >= 0))
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
